import type { EarningsTruthResult } from "@/lib/engines/earnings";

export type GrievancePlatform = "OLA" | "UBER" | "RAPIDO" | "OTHER";

export function buildChallengerComplaint(params: {
  driverName?: string;
  phone: string;
  platform: GrievancePlatform;
  city?: string;
  dateLabel: string;
  inputSummary: string;
  result: EarningsTruthResult;
}): string {
  const name = params.driverName ?? "Driver";
  return `Subject: Payout discrepancy / hidden deduction – ${params.platform} (${params.dateLabel})

Respected Support Team,

I am ${name}, registered driver, mobile ${params.phone}${params.city ? `, city ${params.city}` : ""}.

Summary of issue:
${params.inputSummary}

My calculation (based on trip fares, surge, incentives, and standard commission assumptions) shows expected net approximately ₹${resultFixed(params.result.expectedNet)} whereas I received ₹${resultFixed(params.result.actualPayout)}. Difference: ₹${resultFixed(Math.abs(params.result.variance))} (${params.result.variance < 0 ? "short" : "extra"}).

Please provide:
1. Line-by-line payout breakdown for ${params.dateLabel}.
2. Reason for each deduction/adjustment not visible in trip list.
3. If any policy change affected incentives, share official communication reference.

Attachments I can provide: trip screenshots, payout slip, bank/UPI credit screenshot.

Regards,
${name}
${params.phone}

---
Generated by DriverSaathi (draft). Aap apni zubaan me edit kar sakte ho.`;
}

function resultFixed(n: number) {
  return n.toFixed(2);
}
